version: "3.9"
services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net_4999
      - net_5001
networks:
  net_4999:
    name: party-4999
    external: true
  net_5001:
    name: party-5001
    external: true
